FROM node:14

ARG VITE_COGNITO_USER_POOL_ID
ARG VITE_COGNITO_CLIENT_ID

WORKDIR /code

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

ENV VITE_COGNITO_USER_POOL_ID=$VITE_COGNITO_USER_POOL_ID
ENV VITE_COGNITO_CLIENT_ID=$VITE_COGNITO_CLIENT_ID

CMD ["npm", "run", "docker:dev"]
