version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile${FE_DOCKERFILE_EXT:-}
      args:
        - VITE_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID:-}
        - VITE_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID:-}
        - VITE_FAKE_AUTH_MODE=${FAKE_AUTH_MODE:-}
    volumes:
      - ./frontend:/code
      - /code/node_modules
    ports:
      - 3000:80
    networks:
      - raise
    depends_on:
      - api
  api:
    build:
      context: ./backend
      args:
        - INSTALL_DEV=${INSTALL_DEV:-false}
    volumes:
      - ./backend:/code
    ports:
      - 8000:80
    networks:
      - raise
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=raise
      - POSTGRES_PASSWORD=raise
      - POSTGRES_DB=raise_mgmt
      - POSTGRES_SERVER=postgres
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5000
      - COGNITO_AWS_REGION
      - COGNITO_USER_POOL_ID
      - COGNITO_CLIENT_ID
      - FAKE_AUTH_MODE
  postgres:
    image: "postgres:13"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - raise
    environment:
      - POSTGRES_USER=raise
      - POSTGRES_PASSWORD=raise
      - POSTGRES_DB=raise_mgmt
networks:
  raise:
volumes:
  pgdata:
