/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax RAISE Management Application API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StudyStatusValues,
    StudyStatusValuesFromJSON,
    StudyStatusValuesFromJSONTyped,
    StudyStatusValuesToJSON,
} from './';

/**
 * Study status model
 * @export
 * @interface StudyStatus
 */
export interface StudyStatus {
    /**
     * 
     * @type {StudyStatusValues}
     * @memberof StudyStatus
     */
    status: StudyStatusValues;
}

export function StudyStatusFromJSON(json: any): StudyStatus {
    return StudyStatusFromJSONTyped(json, false);
}

export function StudyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudyStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': StudyStatusValuesFromJSON(json['status']),
    };
}

export function StudyStatusToJSON(value?: StudyStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': StudyStatusValuesToJSON(value.status),
    };
}

