/* tslint:disable */
/* eslint-disable */
/**
 * OpenStax RAISE Management Application API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Study status values
 * @export
 * @enum {string}
 */
export enum StudyStatusValues {
    Submitted = 'SUBMITTED',
    Approved = 'APPROVED',
    Denied = 'DENIED'
}

export function StudyStatusValuesFromJSON(json: any): StudyStatusValues {
    return StudyStatusValuesFromJSONTyped(json, false);
}

export function StudyStatusValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudyStatusValues {
    return json as StudyStatusValues;
}

export function StudyStatusValuesToJSON(value?: StudyStatusValues | null): any {
    return value as any;
}

