"""Add study owner

Revision ID: e228cce706a9
Revises: b49036cff11d
Create Date: 2021-11-01 17:19:17.735989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e228cce706a9'
down_revision = 'b49036cff11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('owner', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'owner')
    # ### end Alembic commands ###
