version: 0.2

env:
  shell: bash
  secrets-manager:
    POSTGRES_USER: "rds-raise-dev:username"
    POSTGRES_PASSWORD: "rds-raise-dev:password"

phases:
  install:
    commands:
      - curl -L https://get.helm.sh/helm-v3.7.2-linux-amd64.tar.gz | tar -xvz
      - mv linux-amd64/helm ./helm
      - curl -L -o yq "https://github.com/mikefarah/yq/releases/download/v4.13.4/yq_linux_amd64"
      - chmod +x ./helm ./yq
      - export PATH=$PWD:$PATH
  pre_build:
    commands:
      - aws eks update-kubeconfig --name $K8S_CLUSTER_NAME
      - export BACKEND_IMAGE_TAG=$(cat $CODEBUILD_SRC_DIR_backend_build_output/backend-image-tag.txt)
      - export FRONTEND_IMAGE_TAG=$(cat $CODEBUILD_SRC_DIR_frontend_build_output/frontend-image-tag.txt)
      - touch ./values.yaml
      - yq e -i '.backendImage=strenv(BACKEND_IMAGE_TAG)' ./values.yaml
      - yq e -i '.cognitoClientId=strenv(COGNITO_CLIENT_ID)' ./values.yaml
      - yq e -i '.cognitoRegion=strenv(COGNITO_AWS_REGION)' ./values.yaml
      - yq e -i '.cognitoUserPoolId=strenv(COGNITO_USER_POOL_ID)' ./values.yaml
      - yq e -i '.domain="rma-dev.raise.openstax.org"' ./values.yaml
      - yq e -i '.frontendImage=strenv(FRONTEND_IMAGE_TAG)' ./values.yaml
      - yq e -i '.pgPassword=strenv(POSTGRES_PASSWORD)' ./values.yaml
      - yq e -i '.pgServer=strenv(POSTGRES_SERVER)' ./values.yaml
      - yq e -i '.pgUsername=strenv(POSTGRES_USER)' ./values.yaml
  build:
    commands:
      - helm upgrade --install -f ./values.yaml raise-management-app deploy/chart/
