---
name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  backend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: |
          ./backend/scripts/lint.sh
  frontend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup
        working-directory: ./frontend
        run: |
          npm install
      - name: Run linter
        working-directory: ./frontend
        run: |
          npm run lint
