---
name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  backend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          ./backend/scripts/test.sh
